### ISSUE TITLE
Starts at last segment

### ISSUE THREAD

**Issue by Brambor** [ROFLailXGOD/TimerPause#5]
Installed the thing, tried out, but it always started at the last segment "Death":
![image](https://github.com/ROFLailXGOD/TimerPause/assets/13402666/21990dbe-1ba6-4156-b36d-4f425c1d95dc)

**Comment by ROFLailXGOD** [comment]
Can you screenshot the Split Editor window?

**Comment by Brambor** [comment]
Layout Editor
![image](https://github.com/ROFLailXGOD/TimerPause/assets/13402666/3f5607ce-14e2-4fb1-853f-bcffed5ff30c)

When I remove the "Timer Pause" it behaves as expected. If I add it back, it doesn't.

Split Editor
![image](https://github.com/ROFLailXGOD/TimerPause/assets/13402666/9d8dd19a-699a-4c2d-a100-6ac769cfdde0)

**Comment by ROFLailXGOD** [comment]
Well, that's expected behaviour. As mentioned in README it currently doesn't work if you already have splits. I hope one day to overcome this, but don't expect it any time soon
